- src: https://github.com/joe--cool/ansible-role-dotfiles
  name: geerlingguy.dotfiles
  version: master

- src: https://github.com/joe--cool/ansible-role-homebrew
  name: geerlingguy.homebrew
  version: master

- src: https://github.com/joe--cool/ansible-role-mas
  name: geerlingguy.mas
  version: master
