---
- name: Create directory of scripts
  copy:
    src: adillow_bin
    dest: "~"
    mode: preserve

- name: Add path for .jenv
  lineinfile:
    path: "~/.zshrc"
    regexp: '^export PATH=\~\/\.jenv'
    line: 'export PATH=~/.jenv/bin:$PATH'

- name: Jenv init
  lineinfile:
    path: "~/.zshrc"
    regexp: '^eval .*jenv init'
    line: 'eval "$(jenv init -)"'

- name: Setup openjdk
  shell: "jenv add {{item}}"
  with_fileglob: '/usr/local/opt/openjdk*'
